---
- name: Install Docker on Test Server
  hosts: slave-node
  become: yes

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

    - name: Update apt package cache (again)
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce docker-ce-cli containerd.io
        state: present

    - name: Add user to the docker group
      user:
        name: "ansible_user"
        groups: docker
        append: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
